apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiops-anomaly-detector
  namespace: default
  labels:
    app: aiops-anomaly-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiops-anomaly-detector
  template:
    metadata:
      labels:
        app: aiops-anomaly-detector
    spec:
      containers:
        - name: anomaly-detector
          image: 122610517295.dkr.ecr.us-east-1.amazonaws.com/aiops-anomaly-detector:v3
          imagePullPolicy: Always
          ports:
            - name: metrics
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: aiops-anomaly-detector
  namespace: default
  labels:
    app: aiops-anomaly-detector
spec:
  selector:
    app: aiops-anomaly-detector
  ports:
    - name: metrics
      port: 8000
      targetPort: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aiops-anomaly-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: aiops-anomaly-detector
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s